// <auto-generated />
namespace SampleCodeFirstIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Shifts_Starts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shifts_Starts));
        
        string IMigrationMetadata.Id
        {
            get { return "201807200250153_Shifts_Starts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
